# Generated by Django 3.0.6 on 2020-05-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MBS', models.TextField(null=True)),
                ('RBS', models.TextField(null=True)),
                ('PGL', models.TextField(null=True)),
                ('VulATP', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_CMAD',
            fields=[
                ('cid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='cid')),
                ('tid', models.IntegerField()),
                ('customerName', models.CharField(max_length=32)),
                ('allowList', models.TextField(null=True)),
                ('valueList', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('rid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='rid')),
                ('tid', models.IntegerField()),
                ('customerName', models.CharField(max_length=32)),
                ('AATP', models.TextField(null=True)),
                ('Astock', models.TextField(null=True)),
                ('cusW', models.FloatField()),
                ('stoW', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('tid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='tid')),
                ('taskName', models.CharField(default='ReCAST Task', max_length=32)),
                ('taskDescription', models.CharField(default='', max_length=128)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('currentPage', models.CharField(default='createTask', max_length=32)),
                ('username', models.CharField(max_length=32, null=True)),
                ('pid', models.CharField(max_length=32, null=True)),
                ('CW_start', models.IntegerField(null=True)),
                ('CW_end', models.IntegerField(null=True)),
                ('enableRub', models.BooleanField(null=True)),
                ('plantATP', models.TextField(null=True)),
                ('ATP_NTA', models.IntegerField(null=True)),
                ('maxDelay', models.IntegerField(null=True)),
                ('packingUnit', models.IntegerField(null=True)),
                ('TA_rid', models.IntegerField(null=True)),
                ('cid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('hassPW', models.CharField(max_length=128)),
                ('userType', models.IntegerField(default=1)),
                ('employeeID', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
